server:
  port: 8081

spring:
  application:
    name: terminal-ms
  boot:
    admin:
      client:
        url: http://localhost:8231

  datasource:
    url: jdbc:mysql://localhost:3306/freight_transport_region_terminal
    username: root
    password: 9398434528
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always